[package]
name = "progresso"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25.0"

# [[bin]]
# name = "simple_example"
# path = "examples/simple.rs"
